services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: claims_user
      POSTGRES_PASSWORD: claims_password
      POSTGRES_DB: healthcare_claims
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/01_create_tables.sql:ro

volumes:
  postgres_data: